// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/zjrosen/perles/internal/beads/domain"
)

// MockIssueWriter is an autogenerated mock type for the IssueWriter type
type MockIssueWriter struct {
	mock.Mock
}

type MockIssueWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIssueWriter) EXPECT() *MockIssueWriter_Expecter {
	return &MockIssueWriter_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function with given fields: issueID, author, text
func (_m *MockIssueWriter) AddComment(issueID string, author string, text string) error {
	ret := _m.Called(issueID, author, text)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(issueID, author, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueWriter_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockIssueWriter_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - issueID string
//   - author string
//   - text string
func (_e *MockIssueWriter_Expecter) AddComment(issueID interface{}, author interface{}, text interface{}) *MockIssueWriter_AddComment_Call {
	return &MockIssueWriter_AddComment_Call{Call: _e.mock.On("AddComment", issueID, author, text)}
}

func (_c *MockIssueWriter_AddComment_Call) Run(run func(issueID string, author string, text string)) *MockIssueWriter_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIssueWriter_AddComment_Call) Return(_a0 error) *MockIssueWriter_AddComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueWriter_AddComment_Call) RunAndReturn(run func(string, string, string) error) *MockIssueWriter_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// AddDependency provides a mock function with given fields: taskID, dependsOnID
func (_m *MockIssueWriter) AddDependency(taskID string, dependsOnID string) error {
	ret := _m.Called(taskID, dependsOnID)

	if len(ret) == 0 {
		panic("no return value specified for AddDependency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(taskID, dependsOnID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueWriter_AddDependency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDependency'
type MockIssueWriter_AddDependency_Call struct {
	*mock.Call
}

// AddDependency is a helper method to define mock.On call
//   - taskID string
//   - dependsOnID string
func (_e *MockIssueWriter_Expecter) AddDependency(taskID interface{}, dependsOnID interface{}) *MockIssueWriter_AddDependency_Call {
	return &MockIssueWriter_AddDependency_Call{Call: _e.mock.On("AddDependency", taskID, dependsOnID)}
}

func (_c *MockIssueWriter_AddDependency_Call) Run(run func(taskID string, dependsOnID string)) *MockIssueWriter_AddDependency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIssueWriter_AddDependency_Call) Return(_a0 error) *MockIssueWriter_AddDependency_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueWriter_AddDependency_Call) RunAndReturn(run func(string, string) error) *MockIssueWriter_AddDependency_Call {
	_c.Call.Return(run)
	return _c
}

// CloseIssue provides a mock function with given fields: issueID, reason
func (_m *MockIssueWriter) CloseIssue(issueID string, reason string) error {
	ret := _m.Called(issueID, reason)

	if len(ret) == 0 {
		panic("no return value specified for CloseIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(issueID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueWriter_CloseIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseIssue'
type MockIssueWriter_CloseIssue_Call struct {
	*mock.Call
}

// CloseIssue is a helper method to define mock.On call
//   - issueID string
//   - reason string
func (_e *MockIssueWriter_Expecter) CloseIssue(issueID interface{}, reason interface{}) *MockIssueWriter_CloseIssue_Call {
	return &MockIssueWriter_CloseIssue_Call{Call: _e.mock.On("CloseIssue", issueID, reason)}
}

func (_c *MockIssueWriter_CloseIssue_Call) Run(run func(issueID string, reason string)) *MockIssueWriter_CloseIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIssueWriter_CloseIssue_Call) Return(_a0 error) *MockIssueWriter_CloseIssue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueWriter_CloseIssue_Call) RunAndReturn(run func(string, string) error) *MockIssueWriter_CloseIssue_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEpic provides a mock function with given fields: title, description, labels
func (_m *MockIssueWriter) CreateEpic(title string, description string, labels []string) (domain.CreateResult, error) {
	ret := _m.Called(title, description, labels)

	if len(ret) == 0 {
		panic("no return value specified for CreateEpic")
	}

	var r0 domain.CreateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, []string) (domain.CreateResult, error)); ok {
		return rf(title, description, labels)
	}
	if rf, ok := ret.Get(0).(func(string, string, []string) domain.CreateResult); ok {
		r0 = rf(title, description, labels)
	} else {
		r0 = ret.Get(0).(domain.CreateResult)
	}

	if rf, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = rf(title, description, labels)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssueWriter_CreateEpic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEpic'
type MockIssueWriter_CreateEpic_Call struct {
	*mock.Call
}

// CreateEpic is a helper method to define mock.On call
//   - title string
//   - description string
//   - labels []string
func (_e *MockIssueWriter_Expecter) CreateEpic(title interface{}, description interface{}, labels interface{}) *MockIssueWriter_CreateEpic_Call {
	return &MockIssueWriter_CreateEpic_Call{Call: _e.mock.On("CreateEpic", title, description, labels)}
}

func (_c *MockIssueWriter_CreateEpic_Call) Run(run func(title string, description string, labels []string)) *MockIssueWriter_CreateEpic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockIssueWriter_CreateEpic_Call) Return(_a0 domain.CreateResult, _a1 error) *MockIssueWriter_CreateEpic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssueWriter_CreateEpic_Call) RunAndReturn(run func(string, string, []string) (domain.CreateResult, error)) *MockIssueWriter_CreateEpic_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: title, description, parentID, assignee, labels
func (_m *MockIssueWriter) CreateTask(title string, description string, parentID string, assignee string, labels []string) (domain.CreateResult, error) {
	ret := _m.Called(title, description, parentID, assignee, labels)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 domain.CreateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, []string) (domain.CreateResult, error)); ok {
		return rf(title, description, parentID, assignee, labels)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, []string) domain.CreateResult); ok {
		r0 = rf(title, description, parentID, assignee, labels)
	} else {
		r0 = ret.Get(0).(domain.CreateResult)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, []string) error); ok {
		r1 = rf(title, description, parentID, assignee, labels)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssueWriter_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockIssueWriter_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - title string
//   - description string
//   - parentID string
//   - assignee string
//   - labels []string
func (_e *MockIssueWriter_Expecter) CreateTask(title interface{}, description interface{}, parentID interface{}, assignee interface{}, labels interface{}) *MockIssueWriter_CreateTask_Call {
	return &MockIssueWriter_CreateTask_Call{Call: _e.mock.On("CreateTask", title, description, parentID, assignee, labels)}
}

func (_c *MockIssueWriter_CreateTask_Call) Run(run func(title string, description string, parentID string, assignee string, labels []string)) *MockIssueWriter_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].([]string))
	})
	return _c
}

func (_c *MockIssueWriter_CreateTask_Call) Return(_a0 domain.CreateResult, _a1 error) *MockIssueWriter_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssueWriter_CreateTask_Call) RunAndReturn(run func(string, string, string, string, []string) (domain.CreateResult, error)) *MockIssueWriter_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIssues provides a mock function with given fields: issueIDs
func (_m *MockIssueWriter) DeleteIssues(issueIDs []string) error {
	ret := _m.Called(issueIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIssues")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(issueIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueWriter_DeleteIssues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIssues'
type MockIssueWriter_DeleteIssues_Call struct {
	*mock.Call
}

// DeleteIssues is a helper method to define mock.On call
//   - issueIDs []string
func (_e *MockIssueWriter_Expecter) DeleteIssues(issueIDs interface{}) *MockIssueWriter_DeleteIssues_Call {
	return &MockIssueWriter_DeleteIssues_Call{Call: _e.mock.On("DeleteIssues", issueIDs)}
}

func (_c *MockIssueWriter_DeleteIssues_Call) Run(run func(issueIDs []string)) *MockIssueWriter_DeleteIssues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockIssueWriter_DeleteIssues_Call) Return(_a0 error) *MockIssueWriter_DeleteIssues_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueWriter_DeleteIssues_Call) RunAndReturn(run func([]string) error) *MockIssueWriter_DeleteIssues_Call {
	_c.Call.Return(run)
	return _c
}

// ReopenIssue provides a mock function with given fields: issueID
func (_m *MockIssueWriter) ReopenIssue(issueID string) error {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for ReopenIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(issueID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueWriter_ReopenIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReopenIssue'
type MockIssueWriter_ReopenIssue_Call struct {
	*mock.Call
}

// ReopenIssue is a helper method to define mock.On call
//   - issueID string
func (_e *MockIssueWriter_Expecter) ReopenIssue(issueID interface{}) *MockIssueWriter_ReopenIssue_Call {
	return &MockIssueWriter_ReopenIssue_Call{Call: _e.mock.On("ReopenIssue", issueID)}
}

func (_c *MockIssueWriter_ReopenIssue_Call) Run(run func(issueID string)) *MockIssueWriter_ReopenIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIssueWriter_ReopenIssue_Call) Return(_a0 error) *MockIssueWriter_ReopenIssue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueWriter_ReopenIssue_Call) RunAndReturn(run func(string) error) *MockIssueWriter_ReopenIssue_Call {
	_c.Call.Return(run)
	return _c
}

// SetLabels provides a mock function with given fields: issueID, labels
func (_m *MockIssueWriter) SetLabels(issueID string, labels []string) error {
	ret := _m.Called(issueID, labels)

	if len(ret) == 0 {
		panic("no return value specified for SetLabels")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(issueID, labels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueWriter_SetLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLabels'
type MockIssueWriter_SetLabels_Call struct {
	*mock.Call
}

// SetLabels is a helper method to define mock.On call
//   - issueID string
//   - labels []string
func (_e *MockIssueWriter_Expecter) SetLabels(issueID interface{}, labels interface{}) *MockIssueWriter_SetLabels_Call {
	return &MockIssueWriter_SetLabels_Call{Call: _e.mock.On("SetLabels", issueID, labels)}
}

func (_c *MockIssueWriter_SetLabels_Call) Run(run func(issueID string, labels []string)) *MockIssueWriter_SetLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockIssueWriter_SetLabels_Call) Return(_a0 error) *MockIssueWriter_SetLabels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueWriter_SetLabels_Call) RunAndReturn(run func(string, []string) error) *MockIssueWriter_SetLabels_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePriority provides a mock function with given fields: issueID, priority
func (_m *MockIssueWriter) UpdatePriority(issueID string, priority domain.Priority) error {
	ret := _m.Called(issueID, priority)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePriority")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.Priority) error); ok {
		r0 = rf(issueID, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueWriter_UpdatePriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePriority'
type MockIssueWriter_UpdatePriority_Call struct {
	*mock.Call
}

// UpdatePriority is a helper method to define mock.On call
//   - issueID string
//   - priority domain.Priority
func (_e *MockIssueWriter_Expecter) UpdatePriority(issueID interface{}, priority interface{}) *MockIssueWriter_UpdatePriority_Call {
	return &MockIssueWriter_UpdatePriority_Call{Call: _e.mock.On("UpdatePriority", issueID, priority)}
}

func (_c *MockIssueWriter_UpdatePriority_Call) Run(run func(issueID string, priority domain.Priority)) *MockIssueWriter_UpdatePriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(domain.Priority))
	})
	return _c
}

func (_c *MockIssueWriter_UpdatePriority_Call) Return(_a0 error) *MockIssueWriter_UpdatePriority_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueWriter_UpdatePriority_Call) RunAndReturn(run func(string, domain.Priority) error) *MockIssueWriter_UpdatePriority_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: issueID, status
func (_m *MockIssueWriter) UpdateStatus(issueID string, status domain.Status) error {
	ret := _m.Called(issueID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.Status) error); ok {
		r0 = rf(issueID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueWriter_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockIssueWriter_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - issueID string
//   - status domain.Status
func (_e *MockIssueWriter_Expecter) UpdateStatus(issueID interface{}, status interface{}) *MockIssueWriter_UpdateStatus_Call {
	return &MockIssueWriter_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", issueID, status)}
}

func (_c *MockIssueWriter_UpdateStatus_Call) Run(run func(issueID string, status domain.Status)) *MockIssueWriter_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(domain.Status))
	})
	return _c
}

func (_c *MockIssueWriter_UpdateStatus_Call) Return(_a0 error) *MockIssueWriter_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueWriter_UpdateStatus_Call) RunAndReturn(run func(string, domain.Status) error) *MockIssueWriter_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateType provides a mock function with given fields: issueID, issueType
func (_m *MockIssueWriter) UpdateType(issueID string, issueType domain.IssueType) error {
	ret := _m.Called(issueID, issueType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.IssueType) error); ok {
		r0 = rf(issueID, issueType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueWriter_UpdateType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateType'
type MockIssueWriter_UpdateType_Call struct {
	*mock.Call
}

// UpdateType is a helper method to define mock.On call
//   - issueID string
//   - issueType domain.IssueType
func (_e *MockIssueWriter_Expecter) UpdateType(issueID interface{}, issueType interface{}) *MockIssueWriter_UpdateType_Call {
	return &MockIssueWriter_UpdateType_Call{Call: _e.mock.On("UpdateType", issueID, issueType)}
}

func (_c *MockIssueWriter_UpdateType_Call) Run(run func(issueID string, issueType domain.IssueType)) *MockIssueWriter_UpdateType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(domain.IssueType))
	})
	return _c
}

func (_c *MockIssueWriter_UpdateType_Call) Return(_a0 error) *MockIssueWriter_UpdateType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueWriter_UpdateType_Call) RunAndReturn(run func(string, domain.IssueType) error) *MockIssueWriter_UpdateType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIssueWriter creates a new instance of MockIssueWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssueWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssueWriter {
	mock := &MockIssueWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
