// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/zjrosen/perles/internal/beads/domain"
)

// MockCommentReader is an autogenerated mock type for the CommentReader type
type MockCommentReader struct {
	mock.Mock
}

type MockCommentReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentReader) EXPECT() *MockCommentReader_Expecter {
	return &MockCommentReader_Expecter{mock: &_m.Mock}
}

// GetComments provides a mock function with given fields: issueID
func (_m *MockCommentReader) GetComments(issueID string) ([]domain.Comment, error) {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Comment, error)); ok {
		return rf(issueID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Comment); ok {
		r0 = rf(issueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(issueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentReader_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockCommentReader_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - issueID string
func (_e *MockCommentReader_Expecter) GetComments(issueID interface{}) *MockCommentReader_GetComments_Call {
	return &MockCommentReader_GetComments_Call{Call: _e.mock.On("GetComments", issueID)}
}

func (_c *MockCommentReader_GetComments_Call) Run(run func(issueID string)) *MockCommentReader_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommentReader_GetComments_Call) Return(_a0 []domain.Comment, _a1 error) *MockCommentReader_GetComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentReader_GetComments_Call) RunAndReturn(run func(string) ([]domain.Comment, error)) *MockCommentReader_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommentReader creates a new instance of MockCommentReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentReader {
	mock := &MockCommentReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
