// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockVersionReader is an autogenerated mock type for the VersionReader type
type MockVersionReader struct {
	mock.Mock
}

type MockVersionReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionReader) EXPECT() *MockVersionReader_Expecter {
	return &MockVersionReader_Expecter{mock: &_m.Mock}
}

// Version provides a mock function with no fields
func (_m *MockVersionReader) Version() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersionReader_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockVersionReader_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockVersionReader_Expecter) Version() *MockVersionReader_Version_Call {
	return &MockVersionReader_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockVersionReader_Version_Call) Run(run func()) *MockVersionReader_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersionReader_Version_Call) Return(_a0 string, _a1 error) *MockVersionReader_Version_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersionReader_Version_Call) RunAndReturn(run func() (string, error)) *MockVersionReader_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVersionReader creates a new instance of MockVersionReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionReader {
	mock := &MockVersionReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
