// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSoundService is an autogenerated mock type for the SoundService type
type MockSoundService struct {
	mock.Mock
}

type MockSoundService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSoundService) EXPECT() *MockSoundService_Expecter {
	return &MockSoundService_Expecter{mock: &_m.Mock}
}

// Play provides a mock function with given fields: soundFile, useCase
func (_m *MockSoundService) Play(soundFile string, useCase string) {
	_m.Called(soundFile, useCase)
}

// MockSoundService_Play_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Play'
type MockSoundService_Play_Call struct {
	*mock.Call
}

// Play is a helper method to define mock.On call
//   - soundFile string
//   - useCase string
func (_e *MockSoundService_Expecter) Play(soundFile interface{}, useCase interface{}) *MockSoundService_Play_Call {
	return &MockSoundService_Play_Call{Call: _e.mock.On("Play", soundFile, useCase)}
}

func (_c *MockSoundService_Play_Call) Run(run func(soundFile string, useCase string)) *MockSoundService_Play_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSoundService_Play_Call) Return() *MockSoundService_Play_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSoundService_Play_Call) RunAndReturn(run func(string, string)) *MockSoundService_Play_Call {
	_c.Run(run)
	return _c
}

// NewMockSoundService creates a new instance of MockSoundService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSoundService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSoundService {
	mock := &MockSoundService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
