// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/zjrosen/perles/internal/beads/domain"
)

// MockIssueReader is an autogenerated mock type for the IssueReader type
type MockIssueReader struct {
	mock.Mock
}

type MockIssueReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIssueReader) EXPECT() *MockIssueReader_Expecter {
	return &MockIssueReader_Expecter{mock: &_m.Mock}
}

// ShowIssue provides a mock function with given fields: issueID
func (_m *MockIssueReader) ShowIssue(issueID string) (*domain.Issue, error) {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for ShowIssue")
	}

	var r0 *domain.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Issue, error)); ok {
		return rf(issueID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Issue); ok {
		r0 = rf(issueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(issueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssueReader_ShowIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowIssue'
type MockIssueReader_ShowIssue_Call struct {
	*mock.Call
}

// ShowIssue is a helper method to define mock.On call
//   - issueID string
func (_e *MockIssueReader_Expecter) ShowIssue(issueID interface{}) *MockIssueReader_ShowIssue_Call {
	return &MockIssueReader_ShowIssue_Call{Call: _e.mock.On("ShowIssue", issueID)}
}

func (_c *MockIssueReader_ShowIssue_Call) Run(run func(issueID string)) *MockIssueReader_ShowIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIssueReader_ShowIssue_Call) Return(_a0 *domain.Issue, _a1 error) *MockIssueReader_ShowIssue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssueReader_ShowIssue_Call) RunAndReturn(run func(string) (*domain.Issue, error)) *MockIssueReader_ShowIssue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIssueReader creates a new instance of MockIssueReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssueReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssueReader {
	mock := &MockIssueReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
