// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/zjrosen/perles/internal/beads/domain"
)

// MockIssueExecutor is an autogenerated mock type for the IssueExecutor type
type MockIssueExecutor struct {
	mock.Mock
}

type MockIssueExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIssueExecutor) EXPECT() *MockIssueExecutor_Expecter {
	return &MockIssueExecutor_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function with given fields: issueID, author, text
func (_m *MockIssueExecutor) AddComment(issueID string, author string, text string) error {
	ret := _m.Called(issueID, author, text)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(issueID, author, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueExecutor_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockIssueExecutor_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - issueID string
//   - author string
//   - text string
func (_e *MockIssueExecutor_Expecter) AddComment(issueID interface{}, author interface{}, text interface{}) *MockIssueExecutor_AddComment_Call {
	return &MockIssueExecutor_AddComment_Call{Call: _e.mock.On("AddComment", issueID, author, text)}
}

func (_c *MockIssueExecutor_AddComment_Call) Run(run func(issueID string, author string, text string)) *MockIssueExecutor_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIssueExecutor_AddComment_Call) Return(_a0 error) *MockIssueExecutor_AddComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueExecutor_AddComment_Call) RunAndReturn(run func(string, string, string) error) *MockIssueExecutor_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// AddDependency provides a mock function with given fields: taskID, dependsOnID
func (_m *MockIssueExecutor) AddDependency(taskID string, dependsOnID string) error {
	ret := _m.Called(taskID, dependsOnID)

	if len(ret) == 0 {
		panic("no return value specified for AddDependency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(taskID, dependsOnID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueExecutor_AddDependency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDependency'
type MockIssueExecutor_AddDependency_Call struct {
	*mock.Call
}

// AddDependency is a helper method to define mock.On call
//   - taskID string
//   - dependsOnID string
func (_e *MockIssueExecutor_Expecter) AddDependency(taskID interface{}, dependsOnID interface{}) *MockIssueExecutor_AddDependency_Call {
	return &MockIssueExecutor_AddDependency_Call{Call: _e.mock.On("AddDependency", taskID, dependsOnID)}
}

func (_c *MockIssueExecutor_AddDependency_Call) Run(run func(taskID string, dependsOnID string)) *MockIssueExecutor_AddDependency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIssueExecutor_AddDependency_Call) Return(_a0 error) *MockIssueExecutor_AddDependency_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueExecutor_AddDependency_Call) RunAndReturn(run func(string, string) error) *MockIssueExecutor_AddDependency_Call {
	_c.Call.Return(run)
	return _c
}

// CloseIssue provides a mock function with given fields: issueID, reason
func (_m *MockIssueExecutor) CloseIssue(issueID string, reason string) error {
	ret := _m.Called(issueID, reason)

	if len(ret) == 0 {
		panic("no return value specified for CloseIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(issueID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueExecutor_CloseIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseIssue'
type MockIssueExecutor_CloseIssue_Call struct {
	*mock.Call
}

// CloseIssue is a helper method to define mock.On call
//   - issueID string
//   - reason string
func (_e *MockIssueExecutor_Expecter) CloseIssue(issueID interface{}, reason interface{}) *MockIssueExecutor_CloseIssue_Call {
	return &MockIssueExecutor_CloseIssue_Call{Call: _e.mock.On("CloseIssue", issueID, reason)}
}

func (_c *MockIssueExecutor_CloseIssue_Call) Run(run func(issueID string, reason string)) *MockIssueExecutor_CloseIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIssueExecutor_CloseIssue_Call) Return(_a0 error) *MockIssueExecutor_CloseIssue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueExecutor_CloseIssue_Call) RunAndReturn(run func(string, string) error) *MockIssueExecutor_CloseIssue_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEpic provides a mock function with given fields: title, description, labels
func (_m *MockIssueExecutor) CreateEpic(title string, description string, labels []string) (domain.CreateResult, error) {
	ret := _m.Called(title, description, labels)

	if len(ret) == 0 {
		panic("no return value specified for CreateEpic")
	}

	var r0 domain.CreateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, []string) (domain.CreateResult, error)); ok {
		return rf(title, description, labels)
	}
	if rf, ok := ret.Get(0).(func(string, string, []string) domain.CreateResult); ok {
		r0 = rf(title, description, labels)
	} else {
		r0 = ret.Get(0).(domain.CreateResult)
	}

	if rf, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = rf(title, description, labels)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssueExecutor_CreateEpic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEpic'
type MockIssueExecutor_CreateEpic_Call struct {
	*mock.Call
}

// CreateEpic is a helper method to define mock.On call
//   - title string
//   - description string
//   - labels []string
func (_e *MockIssueExecutor_Expecter) CreateEpic(title interface{}, description interface{}, labels interface{}) *MockIssueExecutor_CreateEpic_Call {
	return &MockIssueExecutor_CreateEpic_Call{Call: _e.mock.On("CreateEpic", title, description, labels)}
}

func (_c *MockIssueExecutor_CreateEpic_Call) Run(run func(title string, description string, labels []string)) *MockIssueExecutor_CreateEpic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockIssueExecutor_CreateEpic_Call) Return(_a0 domain.CreateResult, _a1 error) *MockIssueExecutor_CreateEpic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssueExecutor_CreateEpic_Call) RunAndReturn(run func(string, string, []string) (domain.CreateResult, error)) *MockIssueExecutor_CreateEpic_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: title, description, parentID, assignee, labels
func (_m *MockIssueExecutor) CreateTask(title string, description string, parentID string, assignee string, labels []string) (domain.CreateResult, error) {
	ret := _m.Called(title, description, parentID, assignee, labels)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 domain.CreateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, []string) (domain.CreateResult, error)); ok {
		return rf(title, description, parentID, assignee, labels)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, []string) domain.CreateResult); ok {
		r0 = rf(title, description, parentID, assignee, labels)
	} else {
		r0 = ret.Get(0).(domain.CreateResult)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, []string) error); ok {
		r1 = rf(title, description, parentID, assignee, labels)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssueExecutor_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockIssueExecutor_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - title string
//   - description string
//   - parentID string
//   - assignee string
//   - labels []string
func (_e *MockIssueExecutor_Expecter) CreateTask(title interface{}, description interface{}, parentID interface{}, assignee interface{}, labels interface{}) *MockIssueExecutor_CreateTask_Call {
	return &MockIssueExecutor_CreateTask_Call{Call: _e.mock.On("CreateTask", title, description, parentID, assignee, labels)}
}

func (_c *MockIssueExecutor_CreateTask_Call) Run(run func(title string, description string, parentID string, assignee string, labels []string)) *MockIssueExecutor_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].([]string))
	})
	return _c
}

func (_c *MockIssueExecutor_CreateTask_Call) Return(_a0 domain.CreateResult, _a1 error) *MockIssueExecutor_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssueExecutor_CreateTask_Call) RunAndReturn(run func(string, string, string, string, []string) (domain.CreateResult, error)) *MockIssueExecutor_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIssues provides a mock function with given fields: issueIDs
func (_m *MockIssueExecutor) DeleteIssues(issueIDs []string) error {
	ret := _m.Called(issueIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIssues")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(issueIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueExecutor_DeleteIssues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIssues'
type MockIssueExecutor_DeleteIssues_Call struct {
	*mock.Call
}

// DeleteIssues is a helper method to define mock.On call
//   - issueIDs []string
func (_e *MockIssueExecutor_Expecter) DeleteIssues(issueIDs interface{}) *MockIssueExecutor_DeleteIssues_Call {
	return &MockIssueExecutor_DeleteIssues_Call{Call: _e.mock.On("DeleteIssues", issueIDs)}
}

func (_c *MockIssueExecutor_DeleteIssues_Call) Run(run func(issueIDs []string)) *MockIssueExecutor_DeleteIssues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockIssueExecutor_DeleteIssues_Call) Return(_a0 error) *MockIssueExecutor_DeleteIssues_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueExecutor_DeleteIssues_Call) RunAndReturn(run func([]string) error) *MockIssueExecutor_DeleteIssues_Call {
	_c.Call.Return(run)
	return _c
}

// ReopenIssue provides a mock function with given fields: issueID
func (_m *MockIssueExecutor) ReopenIssue(issueID string) error {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for ReopenIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(issueID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueExecutor_ReopenIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReopenIssue'
type MockIssueExecutor_ReopenIssue_Call struct {
	*mock.Call
}

// ReopenIssue is a helper method to define mock.On call
//   - issueID string
func (_e *MockIssueExecutor_Expecter) ReopenIssue(issueID interface{}) *MockIssueExecutor_ReopenIssue_Call {
	return &MockIssueExecutor_ReopenIssue_Call{Call: _e.mock.On("ReopenIssue", issueID)}
}

func (_c *MockIssueExecutor_ReopenIssue_Call) Run(run func(issueID string)) *MockIssueExecutor_ReopenIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIssueExecutor_ReopenIssue_Call) Return(_a0 error) *MockIssueExecutor_ReopenIssue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueExecutor_ReopenIssue_Call) RunAndReturn(run func(string) error) *MockIssueExecutor_ReopenIssue_Call {
	_c.Call.Return(run)
	return _c
}

// SetLabels provides a mock function with given fields: issueID, labels
func (_m *MockIssueExecutor) SetLabels(issueID string, labels []string) error {
	ret := _m.Called(issueID, labels)

	if len(ret) == 0 {
		panic("no return value specified for SetLabels")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(issueID, labels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueExecutor_SetLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLabels'
type MockIssueExecutor_SetLabels_Call struct {
	*mock.Call
}

// SetLabels is a helper method to define mock.On call
//   - issueID string
//   - labels []string
func (_e *MockIssueExecutor_Expecter) SetLabels(issueID interface{}, labels interface{}) *MockIssueExecutor_SetLabels_Call {
	return &MockIssueExecutor_SetLabels_Call{Call: _e.mock.On("SetLabels", issueID, labels)}
}

func (_c *MockIssueExecutor_SetLabels_Call) Run(run func(issueID string, labels []string)) *MockIssueExecutor_SetLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockIssueExecutor_SetLabels_Call) Return(_a0 error) *MockIssueExecutor_SetLabels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueExecutor_SetLabels_Call) RunAndReturn(run func(string, []string) error) *MockIssueExecutor_SetLabels_Call {
	_c.Call.Return(run)
	return _c
}

// ShowIssue provides a mock function with given fields: issueID
func (_m *MockIssueExecutor) ShowIssue(issueID string) (*domain.Issue, error) {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for ShowIssue")
	}

	var r0 *domain.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Issue, error)); ok {
		return rf(issueID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Issue); ok {
		r0 = rf(issueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(issueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssueExecutor_ShowIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowIssue'
type MockIssueExecutor_ShowIssue_Call struct {
	*mock.Call
}

// ShowIssue is a helper method to define mock.On call
//   - issueID string
func (_e *MockIssueExecutor_Expecter) ShowIssue(issueID interface{}) *MockIssueExecutor_ShowIssue_Call {
	return &MockIssueExecutor_ShowIssue_Call{Call: _e.mock.On("ShowIssue", issueID)}
}

func (_c *MockIssueExecutor_ShowIssue_Call) Run(run func(issueID string)) *MockIssueExecutor_ShowIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIssueExecutor_ShowIssue_Call) Return(_a0 *domain.Issue, _a1 error) *MockIssueExecutor_ShowIssue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssueExecutor_ShowIssue_Call) RunAndReturn(run func(string) (*domain.Issue, error)) *MockIssueExecutor_ShowIssue_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDescription provides a mock function with given fields: issueID, description
func (_m *MockIssueExecutor) UpdateDescription(issueID string, description string) error {
	ret := _m.Called(issueID, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDescription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(issueID, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueExecutor_UpdateDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDescription'
type MockIssueExecutor_UpdateDescription_Call struct {
	*mock.Call
}

// UpdateDescription is a helper method to define mock.On call
//   - issueID string
//   - description string
func (_e *MockIssueExecutor_Expecter) UpdateDescription(issueID interface{}, description interface{}) *MockIssueExecutor_UpdateDescription_Call {
	return &MockIssueExecutor_UpdateDescription_Call{Call: _e.mock.On("UpdateDescription", issueID, description)}
}

func (_c *MockIssueExecutor_UpdateDescription_Call) Run(run func(issueID string, description string)) *MockIssueExecutor_UpdateDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIssueExecutor_UpdateDescription_Call) Return(_a0 error) *MockIssueExecutor_UpdateDescription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueExecutor_UpdateDescription_Call) RunAndReturn(run func(string, string) error) *MockIssueExecutor_UpdateDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePriority provides a mock function with given fields: issueID, priority
func (_m *MockIssueExecutor) UpdatePriority(issueID string, priority domain.Priority) error {
	ret := _m.Called(issueID, priority)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePriority")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.Priority) error); ok {
		r0 = rf(issueID, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueExecutor_UpdatePriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePriority'
type MockIssueExecutor_UpdatePriority_Call struct {
	*mock.Call
}

// UpdatePriority is a helper method to define mock.On call
//   - issueID string
//   - priority domain.Priority
func (_e *MockIssueExecutor_Expecter) UpdatePriority(issueID interface{}, priority interface{}) *MockIssueExecutor_UpdatePriority_Call {
	return &MockIssueExecutor_UpdatePriority_Call{Call: _e.mock.On("UpdatePriority", issueID, priority)}
}

func (_c *MockIssueExecutor_UpdatePriority_Call) Run(run func(issueID string, priority domain.Priority)) *MockIssueExecutor_UpdatePriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(domain.Priority))
	})
	return _c
}

func (_c *MockIssueExecutor_UpdatePriority_Call) Return(_a0 error) *MockIssueExecutor_UpdatePriority_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueExecutor_UpdatePriority_Call) RunAndReturn(run func(string, domain.Priority) error) *MockIssueExecutor_UpdatePriority_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: issueID, status
func (_m *MockIssueExecutor) UpdateStatus(issueID string, status domain.Status) error {
	ret := _m.Called(issueID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.Status) error); ok {
		r0 = rf(issueID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueExecutor_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockIssueExecutor_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - issueID string
//   - status domain.Status
func (_e *MockIssueExecutor_Expecter) UpdateStatus(issueID interface{}, status interface{}) *MockIssueExecutor_UpdateStatus_Call {
	return &MockIssueExecutor_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", issueID, status)}
}

func (_c *MockIssueExecutor_UpdateStatus_Call) Run(run func(issueID string, status domain.Status)) *MockIssueExecutor_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(domain.Status))
	})
	return _c
}

func (_c *MockIssueExecutor_UpdateStatus_Call) Return(_a0 error) *MockIssueExecutor_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueExecutor_UpdateStatus_Call) RunAndReturn(run func(string, domain.Status) error) *MockIssueExecutor_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateType provides a mock function with given fields: issueID, issueType
func (_m *MockIssueExecutor) UpdateType(issueID string, issueType domain.IssueType) error {
	ret := _m.Called(issueID, issueType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.IssueType) error); ok {
		r0 = rf(issueID, issueType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssueExecutor_UpdateType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateType'
type MockIssueExecutor_UpdateType_Call struct {
	*mock.Call
}

// UpdateType is a helper method to define mock.On call
//   - issueID string
//   - issueType domain.IssueType
func (_e *MockIssueExecutor_Expecter) UpdateType(issueID interface{}, issueType interface{}) *MockIssueExecutor_UpdateType_Call {
	return &MockIssueExecutor_UpdateType_Call{Call: _e.mock.On("UpdateType", issueID, issueType)}
}

func (_c *MockIssueExecutor_UpdateType_Call) Run(run func(issueID string, issueType domain.IssueType)) *MockIssueExecutor_UpdateType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(domain.IssueType))
	})
	return _c
}

func (_c *MockIssueExecutor_UpdateType_Call) Return(_a0 error) *MockIssueExecutor_UpdateType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssueExecutor_UpdateType_Call) RunAndReturn(run func(string, domain.IssueType) error) *MockIssueExecutor_UpdateType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIssueExecutor creates a new instance of MockIssueExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssueExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssueExecutor {
	mock := &MockIssueExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
