// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	controlplane "github.com/zjrosen/perles/internal/orchestration/controlplane"
)

// MockHealthMonitor is an autogenerated mock type for the HealthMonitor type
type MockHealthMonitor struct {
	mock.Mock
}

type MockHealthMonitor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthMonitor) EXPECT() *MockHealthMonitor_Expecter {
	return &MockHealthMonitor_Expecter{mock: &_m.Mock}
}

// GetAllStatuses provides a mock function with no fields
func (_m *MockHealthMonitor) GetAllStatuses() []controlplane.HealthStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllStatuses")
	}

	var r0 []controlplane.HealthStatus
	if rf, ok := ret.Get(0).(func() []controlplane.HealthStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]controlplane.HealthStatus)
		}
	}

	return r0
}

// MockHealthMonitor_GetAllStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStatuses'
type MockHealthMonitor_GetAllStatuses_Call struct {
	*mock.Call
}

// GetAllStatuses is a helper method to define mock.On call
func (_e *MockHealthMonitor_Expecter) GetAllStatuses() *MockHealthMonitor_GetAllStatuses_Call {
	return &MockHealthMonitor_GetAllStatuses_Call{Call: _e.mock.On("GetAllStatuses")}
}

func (_c *MockHealthMonitor_GetAllStatuses_Call) Run(run func()) *MockHealthMonitor_GetAllStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthMonitor_GetAllStatuses_Call) Return(_a0 []controlplane.HealthStatus) *MockHealthMonitor_GetAllStatuses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthMonitor_GetAllStatuses_Call) RunAndReturn(run func() []controlplane.HealthStatus) *MockHealthMonitor_GetAllStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: id
func (_m *MockHealthMonitor) GetStatus(id controlplane.WorkflowID) (controlplane.HealthStatus, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 controlplane.HealthStatus
	var r1 bool
	if rf, ok := ret.Get(0).(func(controlplane.WorkflowID) (controlplane.HealthStatus, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(controlplane.WorkflowID) controlplane.HealthStatus); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(controlplane.HealthStatus)
	}

	if rf, ok := ret.Get(1).(func(controlplane.WorkflowID) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockHealthMonitor_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockHealthMonitor_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - id controlplane.WorkflowID
func (_e *MockHealthMonitor_Expecter) GetStatus(id interface{}) *MockHealthMonitor_GetStatus_Call {
	return &MockHealthMonitor_GetStatus_Call{Call: _e.mock.On("GetStatus", id)}
}

func (_c *MockHealthMonitor_GetStatus_Call) Run(run func(id controlplane.WorkflowID)) *MockHealthMonitor_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(controlplane.WorkflowID))
	})
	return _c
}

func (_c *MockHealthMonitor_GetStatus_Call) Return(_a0 controlplane.HealthStatus, _a1 bool) *MockHealthMonitor_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHealthMonitor_GetStatus_Call) RunAndReturn(run func(controlplane.WorkflowID) (controlplane.HealthStatus, bool)) *MockHealthMonitor_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RecordHeartbeat provides a mock function with given fields: id
func (_m *MockHealthMonitor) RecordHeartbeat(id controlplane.WorkflowID) {
	_m.Called(id)
}

// MockHealthMonitor_RecordHeartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordHeartbeat'
type MockHealthMonitor_RecordHeartbeat_Call struct {
	*mock.Call
}

// RecordHeartbeat is a helper method to define mock.On call
//   - id controlplane.WorkflowID
func (_e *MockHealthMonitor_Expecter) RecordHeartbeat(id interface{}) *MockHealthMonitor_RecordHeartbeat_Call {
	return &MockHealthMonitor_RecordHeartbeat_Call{Call: _e.mock.On("RecordHeartbeat", id)}
}

func (_c *MockHealthMonitor_RecordHeartbeat_Call) Run(run func(id controlplane.WorkflowID)) *MockHealthMonitor_RecordHeartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(controlplane.WorkflowID))
	})
	return _c
}

func (_c *MockHealthMonitor_RecordHeartbeat_Call) Return() *MockHealthMonitor_RecordHeartbeat_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_RecordHeartbeat_Call) RunAndReturn(run func(controlplane.WorkflowID)) *MockHealthMonitor_RecordHeartbeat_Call {
	_c.Run(run)
	return _c
}

// RecordProgress provides a mock function with given fields: id
func (_m *MockHealthMonitor) RecordProgress(id controlplane.WorkflowID) {
	_m.Called(id)
}

// MockHealthMonitor_RecordProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordProgress'
type MockHealthMonitor_RecordProgress_Call struct {
	*mock.Call
}

// RecordProgress is a helper method to define mock.On call
//   - id controlplane.WorkflowID
func (_e *MockHealthMonitor_Expecter) RecordProgress(id interface{}) *MockHealthMonitor_RecordProgress_Call {
	return &MockHealthMonitor_RecordProgress_Call{Call: _e.mock.On("RecordProgress", id)}
}

func (_c *MockHealthMonitor_RecordProgress_Call) Run(run func(id controlplane.WorkflowID)) *MockHealthMonitor_RecordProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(controlplane.WorkflowID))
	})
	return _c
}

func (_c *MockHealthMonitor_RecordProgress_Call) Return() *MockHealthMonitor_RecordProgress_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_RecordProgress_Call) RunAndReturn(run func(controlplane.WorkflowID)) *MockHealthMonitor_RecordProgress_Call {
	_c.Run(run)
	return _c
}

// SetPolicy provides a mock function with given fields: policy
func (_m *MockHealthMonitor) SetPolicy(policy controlplane.HealthPolicy) {
	_m.Called(policy)
}

// MockHealthMonitor_SetPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPolicy'
type MockHealthMonitor_SetPolicy_Call struct {
	*mock.Call
}

// SetPolicy is a helper method to define mock.On call
//   - policy controlplane.HealthPolicy
func (_e *MockHealthMonitor_Expecter) SetPolicy(policy interface{}) *MockHealthMonitor_SetPolicy_Call {
	return &MockHealthMonitor_SetPolicy_Call{Call: _e.mock.On("SetPolicy", policy)}
}

func (_c *MockHealthMonitor_SetPolicy_Call) Run(run func(policy controlplane.HealthPolicy)) *MockHealthMonitor_SetPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(controlplane.HealthPolicy))
	})
	return _c
}

func (_c *MockHealthMonitor_SetPolicy_Call) Return() *MockHealthMonitor_SetPolicy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_SetPolicy_Call) RunAndReturn(run func(controlplane.HealthPolicy)) *MockHealthMonitor_SetPolicy_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockHealthMonitor) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthMonitor_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockHealthMonitor_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthMonitor_Expecter) Start(ctx interface{}) *MockHealthMonitor_Start_Call {
	return &MockHealthMonitor_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockHealthMonitor_Start_Call) Run(run func(ctx context.Context)) *MockHealthMonitor_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthMonitor_Start_Call) Return(_a0 error) *MockHealthMonitor_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthMonitor_Start_Call) RunAndReturn(run func(context.Context) error) *MockHealthMonitor_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockHealthMonitor) Stop() {
	_m.Called()
}

// MockHealthMonitor_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockHealthMonitor_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockHealthMonitor_Expecter) Stop() *MockHealthMonitor_Stop_Call {
	return &MockHealthMonitor_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockHealthMonitor_Stop_Call) Run(run func()) *MockHealthMonitor_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthMonitor_Stop_Call) Return() *MockHealthMonitor_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_Stop_Call) RunAndReturn(run func()) *MockHealthMonitor_Stop_Call {
	_c.Run(run)
	return _c
}

// TrackWorkflow provides a mock function with given fields: id
func (_m *MockHealthMonitor) TrackWorkflow(id controlplane.WorkflowID) {
	_m.Called(id)
}

// MockHealthMonitor_TrackWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackWorkflow'
type MockHealthMonitor_TrackWorkflow_Call struct {
	*mock.Call
}

// TrackWorkflow is a helper method to define mock.On call
//   - id controlplane.WorkflowID
func (_e *MockHealthMonitor_Expecter) TrackWorkflow(id interface{}) *MockHealthMonitor_TrackWorkflow_Call {
	return &MockHealthMonitor_TrackWorkflow_Call{Call: _e.mock.On("TrackWorkflow", id)}
}

func (_c *MockHealthMonitor_TrackWorkflow_Call) Run(run func(id controlplane.WorkflowID)) *MockHealthMonitor_TrackWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(controlplane.WorkflowID))
	})
	return _c
}

func (_c *MockHealthMonitor_TrackWorkflow_Call) Return() *MockHealthMonitor_TrackWorkflow_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_TrackWorkflow_Call) RunAndReturn(run func(controlplane.WorkflowID)) *MockHealthMonitor_TrackWorkflow_Call {
	_c.Run(run)
	return _c
}

// UntrackWorkflow provides a mock function with given fields: id
func (_m *MockHealthMonitor) UntrackWorkflow(id controlplane.WorkflowID) {
	_m.Called(id)
}

// MockHealthMonitor_UntrackWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UntrackWorkflow'
type MockHealthMonitor_UntrackWorkflow_Call struct {
	*mock.Call
}

// UntrackWorkflow is a helper method to define mock.On call
//   - id controlplane.WorkflowID
func (_e *MockHealthMonitor_Expecter) UntrackWorkflow(id interface{}) *MockHealthMonitor_UntrackWorkflow_Call {
	return &MockHealthMonitor_UntrackWorkflow_Call{Call: _e.mock.On("UntrackWorkflow", id)}
}

func (_c *MockHealthMonitor_UntrackWorkflow_Call) Run(run func(id controlplane.WorkflowID)) *MockHealthMonitor_UntrackWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(controlplane.WorkflowID))
	})
	return _c
}

func (_c *MockHealthMonitor_UntrackWorkflow_Call) Return() *MockHealthMonitor_UntrackWorkflow_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_UntrackWorkflow_Call) RunAndReturn(run func(controlplane.WorkflowID)) *MockHealthMonitor_UntrackWorkflow_Call {
	_c.Run(run)
	return _c
}

// NewMockHealthMonitor creates a new instance of MockHealthMonitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthMonitor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthMonitor {
	mock := &MockHealthMonitor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
