with-expecter: true
dir: internal/mocks
outpkg: mocks
packages:
  github.com/zjrosen/perles/internal/mode:
    interfaces:
      BeadsClient:
  github.com/zjrosen/perles/internal/beads/application:
    interfaces:
      VersionReader:
      CommentReader:
      IssueReader:
      IssueWriter:
      IssueExecutor:
  github.com/zjrosen/perles/internal/bql:
    interfaces:
      BQLExecutor:
  github.com/zjrosen/perles/internal/cachemanager:
    interfaces:
      CacheManager:
  github.com/zjrosen/perles/internal/mode/shared:
    interfaces:
      Clock:
      Clipboard:
  github.com/zjrosen/perles/internal/orchestration/client:
    interfaces:
      AgentProvider:
      HeadlessClient:
      HeadlessProcess:
  github.com/zjrosen/perles/internal/git/application:
    interfaces:
      GitExecutor:
  github.com/zjrosen/perles/internal/sound:
    interfaces:
      SoundService:
  github.com/zjrosen/perles/internal/orchestration/controlplane:
    config:
      dir: internal/orchestration/controlplane/mocks
      outpkg: mocks
    interfaces:
      ControlPlane:
      HealthMonitor:
