// Package metrics provides token usage and cost tracking for orchestration mode.
package metrics

import (
	"fmt"
	"time"
)

// TokenMetrics holds token usage and cost data for a coordinator or worker.
type TokenMetrics struct {
	// Context tracking (simplified: two numbers only)
	TokensUsed   int `json:"tokens_used"`   // Cumulative context tokens (input + cache_read + cache_create)
	TotalTokens  int `json:"total_tokens"`  // Context window size (default 200000)
	OutputTokens int `json:"output_tokens"` // Tokens generated by model this turn

	// Cost tracking
	TurnCostUSD       float64 `json:"turn_cost_usd"`
	TotalCostUSD      float64 `json:"total_cost_usd"`
	CumulativeCostUSD float64 `json:"cumulative_cost_usd"` // Running total across all turns

	// Metadata
	LastUpdatedAt time.Time `json:"last_updated_at"`
}

// ContextUsage returns the percentage of context window used (0-100).
func (m TokenMetrics) ContextUsage() float64 {
	if m.TotalTokens == 0 {
		return 0
	}
	return float64(m.TokensUsed) / float64(m.TotalTokens) * 100
}

// FormatContextDisplay returns a human-readable context usage string (e.g., "27k/200k").
func (m TokenMetrics) FormatContextDisplay() string {
	if m.TotalTokens == 0 {
		return "-"
	}
	return fmt.Sprintf("%dk/%dk", m.TokensUsed/1000, m.TotalTokens/1000)
}

// FormatCostDisplay returns a human-readable cost string (e.g., "$0.0892").
func (m TokenMetrics) FormatCostDisplay() string {
	return fmt.Sprintf("$%.4f", m.TotalCostUSD)
}
